name: Docker CI pipeline

on:
    push:
        branches:
            - main
            - pw

    pull_request:
        branches:
            - main
            - pw

jobs:
    docker:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Build Docker image
              run: docker build -t python-ci-local .

            - name: Run Docker image
              run: docker run python-ci-local
